services:
  nginx:
    environment:
      - SERVER_IP=$CONTAINER_IP
      - SERVER_PORT=$COMTAINER_PORT
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    pull_policy: build
    network_mode: bridge
    ports:
      - 80:80
    volumes:
      - static_files:/home/app/staticfiles
  # dns:
  #   build:
  #     context: ./dns/
  #     dockerfile: Dockerfile
  #   pull_policy: build
  #   network_mode: bridge
  #   restart: always
  #   ports:
  #     - 53:53
  #     - 53:53/udp
  #   command: named -c /etc/bind/named.conf -g -u named

volumes:
  static_files:
    name: menu_osseloa_web
    external: true
